ContactWeb/Models/Contact.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ContactWeb.Models
{
    public class Contact
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "First Name is Required")]
        [StringLength(ContactWebConstants.MAX_FIRST_NAME_LENGTH)]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Last Name is Required")]
        [StringLength(ContactWebConstants.MAX_FIRST_NAME_LENGTH)]
        public string LastName { get; set; }

        [Display(Name = "Email Address")]
        [Required(ErrorMessage ="Email is Required")]
        [EmailAddress(ErrorMessage ="Invalid Email Address")]
        [StringLength(ContactWebConstants.MAX_EMAIL_LENGTH)]
        public string Email { get; set; }

        [Display(Name = "Mobile Phone")]
        [Required(ErrorMessage ="Phone is Required")]
        [Phone(ErrorMessage ="Invalid Phone Number")]
        [StringLength(ContactWebConstants.MAX_PHONE_LENGTH)]
        public string PhonePrimary { get; set; }

        [Display(Name = "Home/Office Phone")]
        [Phone(ErrorMessage = "Invalid Phone Number")]
        [StringLength(ContactWebConstants.MAX_PHONE_LENGTH)]
        public string PhoneSecondary { get; set; }

        [DataType(DataType.Date)]
        public DateTime Birthday { get; set; }

        [Display(Name = "Street Address Line 1")]
        [StringLength(ContactWebConstants.MAX_STREET_ADDRESS_LENGTH)]
        public string StreetAddress1 { get; set; }

        [Display(Name = "Street Address Line 2")]
        [StringLength(ContactWebConstants.MAX_STREET_ADDRESS_LENGTH)]
        public string StreetAddress2 { get; set; }

        [Required(ErrorMessage = "City is Required")]
        [StringLength(ContactWebConstants.MAX_CITY_LENGTH)]
        public string City { get; set; }

        [Display(Name = "State")]
        [Required(ErrorMessage = "State is Required")]
        public int StateId { get; set; } 
        public virtual State State { get; set; }

        [Required(ErrorMessage = "Zip Code is Required")]
        [Display(Name ="Zip Code")]
        [RegularExpression("(^\\d{5}(-\\d{4})?$)|(^[ABCEGHJKLMNPRSTVXY]{1}\\d{1}[A-Z]{1} *\\d{1}[A-Z]{1}\\d{1}$)", ErrorMessage = "Zip code is invalid.")] // US or Canada
        [StringLength(ContactWebConstants.MAX_ZIP_CODE_LENGTH, MinimumLength = ContactWebConstants.MIN_ZIP_CODE_LENGTH)]
        public string Zip { get; set; }

        [Required]
        public string UserId { get; set; }
        public virtual ApplicationUser User { get; set; }

        [Display(Name ="Full Name")]
        public string FriendlyName => $"{FirstName} {LastName}";

        [Display(Name = "Full Address")]
        public string FriendlyAddress => string.IsNullOrWhiteSpace(StreetAddress1) ? $"{City}, {State.Abbreviation}, {Zip}" :
                                         string.IsNullOrWhiteSpace(StreetAddress2)
                                            ? $"{StreetAddress1}, {City}, {State.Abbreviation}, {Zip}"
                                            : $"{StreetAddress1}, {StreetAddress2}, {City}, {State.Abbreviation}, {Zip}";
    }
}

ContactWeb/Controllers/ContactsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ContactWeb.Models;
using Microsoft.AspNet.Identity;

namespace ContactWeb.Controllers
{
    [Authorize]
    public class ContactsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private string _userId;

        // GET: Contacts
        public ActionResult Index()
        {
            _userId = GetCurrentUserId();
            var contacts = db.Contacts.Include(c => c.State)
                                      .Include(c => c.User)
                                      .Where(x => x.UserId == _userId);
            return View(contacts.ToList());
        }

        // GET: Contacts/Details/5
        public ActionResult Details(int? id)
        {
            _userId = GetCurrentUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.FirstOrDefault(x => x.Id == id && x.UserId == _userId);
            if (contact == null)
            {
                return HttpNotFound();
            }
            return View(contact);
        }

        // GET: Contacts/Create
        public ActionResult Create()
        {
            _userId = GetCurrentUserId();
            ViewBag.StateId = new SelectList(db.States, "Id", "Name");
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Email,PhonePrimary,PhoneSecondary,Birthday,StreetAddress1,StreetAddress2,City,StateId,Zip,UserId")] Contact contact)
        {
            _userId = GetCurrentUserId();
            contact.UserId = _userId;
            ModelState.Clear();
            TryValidateModel(contact);

            if (ModelState.IsValid)
            {
                db.Contacts.Add(contact);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StateId = new SelectList(db.States, "Id", "Name", contact.StateId);
            return View(contact);
        }

        // GET: Contacts/Edit/5
        public ActionResult Edit(int? id)
        {
            _userId = GetCurrentUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contact contact = db.Contacts.FirstOrDefault(x => x.Id == id && x.UserId == _userId);
            if (contact == null)
            {
                return HttpNotFound();
            }
            ViewBag.StateId = new SelectList(db.States, "Id", "Name", contact.StateId);
            return View(contact);
        }

        // POST: Contacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Email,PhonePrimary,PhoneSecondary,Birthday,StreetAddress1,StreetAddress2,City,StateId,Zip")] Contact contact)
        {
            _userId = GetCurrentUserId();
            var existing = db.Contacts.AsNoTracking().FirstOrDefault(x => x.Id == contact.Id && x.UserId == _userId);
            if (existing == null) return HttpNotFound();

            contact.UserId = _userId;
            ModelState.Clear();
            TryValidateModel(contact);

            if (ModelState.IsValid)
            {
                db.Entry(contact).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StateId = new SelectList(db.States, "Id", "Name", contact.StateId);
            return View(contact);
        }

        // GET: Contacts/Delete/5
        public ActionResult Delete(int? id)
        {
            _userId = GetCurrentUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var existing = db.Contacts.FirstOrDefault(x => x.Id == id && x.UserId == _userId);
            if (existing == null) return HttpNotFound();

            return View(existing);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _userId = GetCurrentUserId();
            Contact contact = db.Contacts.FirstOrDefault(x => x.Id == id && x.UserId == _userId);
            db.Contacts.Remove(contact);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        protected string GetCurrentUserId()
        {
            return User.Identity.GetUserId();
        }
    }
}

ContactWeb/Views/Contacts/Create.cshtml
@model ContactWeb.Models.Contact

@{
    ViewBag.Title = "Create";
}

<h2>@ViewBag.Title Contact</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <hr />

    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label" }) *
                    <div class="">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label" }) *
                    <div class="">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" }) *
                    <div class="">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.PhonePrimary, htmlAttributes: new { @class = "control-label" }) *
                    <div class="">
                        @Html.EditorFor(model => model.PhonePrimary, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhonePrimary, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.PhoneSecondary, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.PhoneSecondary, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhoneSecondary, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.StreetAddress1, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.StreetAddress1, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StreetAddress1, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.StreetAddress2, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.StreetAddress2, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StreetAddress2, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">

            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label" }) *
                    <div class="">
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.StateId, "State", htmlAttributes: new { @class = "control-label" }) *
                    <div class="">
                        @Html.DropDownList("StateId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label" }) *
                    <div class="">
                        @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="padding-top: 25px;">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <span>* indicates required fields</span>
            </div>
        </div>
        <div class="row" style="padding-top: 25px;">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <input type="submit" value="Create" class="btn btn-default" style="width:100%;" />
            </div>
        </div>
        <div class="row" style="padding-top: 25px;">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContactWeb/Views/Contacts/Delete.cshtml
@model ContactWeb.Models.Contact

@{
    ViewBag.Title = "Delete";
}

<h3>Are you sure you want to delete the contact: @Model.FriendlyName?</h3>
<div>
    <h4>Contact</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FriendlyName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FriendlyName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        @if (Model.Birthday != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Birthday)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Birthday)
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.PhonePrimary)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhonePrimary)
        </dd>

        @if (!string.IsNullOrWhiteSpace(Model.PhoneSecondary))
        {
            <dt>
                @Html.DisplayNameFor(model => model.PhoneSecondary)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PhoneSecondary)
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.FriendlyAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FriendlyAddress)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ContactWeb/Views/Contacts/Details.cshtml
@model ContactWeb.Models.Contact

@{
    ViewBag.Title = "Details";
}

<h2>@ViewBag.Title - @Model.FriendlyName</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FriendlyName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FriendlyName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        @if (Model.Birthday != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Birthday)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Birthday)
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.PhonePrimary)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhonePrimary)
        </dd>

        @if (!string.IsNullOrWhiteSpace(Model.PhoneSecondary))
        {
            <dt>
                @Html.DisplayNameFor(model => model.PhoneSecondary)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PhoneSecondary)
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.FriendlyAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FriendlyAddress)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ContactWeb/Views/Contacts/Edit.cshtml
@model ContactWeb.Models.Contact

@{
    ViewBag.Title = "Edit";
}

<h2>@ViewBag.Title - @Model.FriendlyName</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <hr />

    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label" }) *
                    <div class="">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label" }) *
                    <div class="">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" }) *
                    <div class="">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.PhonePrimary, htmlAttributes: new { @class = "control-label" }) *
                    <div class="">
                        @Html.EditorFor(model => model.PhonePrimary, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhonePrimary, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.PhoneSecondary, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.PhoneSecondary, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhoneSecondary, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @*@Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })*@
                        @Html.TextBoxFor(model => model.Birthday, "{0:yyyy-MM-dd}", new { @class = "form-control", @type="date"})
                        @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.StreetAddress1, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.StreetAddress1, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StreetAddress1, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.StreetAddress2, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.StreetAddress2, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StreetAddress2, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">

            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label" }) *
                    <div class="">
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.StateId, "State", htmlAttributes: new { @class = "control-label" }) *
                    <div class="">
                        @Html.DropDownList("StateId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label" }) *
                    <div class="">
                        @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row" style="padding-top: 25px;">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <span>* indicates required fields</span>
            </div>
        </div>
        <div class="row" style="padding-top: 25px;">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                <input type="submit" value="Save" class="btn btn-default" style="width:100%;" />
            </div>
        </div>
        <div class="row" style="padding-top: 25px;">
            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContactWeb/Views/Contacts/Index.cshtml
@model IEnumerable<ContactWeb.Models.Contact>

@{
    ViewBag.Title = "Index";
}

<div class="row" style="padding:25px">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-4">
        <hs>My Contacts</hs>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 col-xl-4">
        @Html.ActionLink("Create New", "Create","Contacts", null, new { @class = "btn btn-default float-right", style = "min-width: 150px" })
    </div>
</div>

<hr/>

<table id="contacts_table" class="display" style="width:100%;">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.State.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhonePrimary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneSecondary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Birthday)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StreetAddress1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StreetAddress2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zip)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.State.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhonePrimary)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneSecondary)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Birthday)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StreetAddress1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StreetAddress2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Zip)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts 
{
    <script type="text/javascript">
        $("#contacts_table").DataTable();
    </script>
}